services:
    felt-app:
        build: ./flet-dock
        image: my-flet-app
        container_name: new-flet-app
        tty: true
        cap_add:
            - ALL
        privileged: true
        # command: bash -c "/bin/bash"
        environment:
          - DISPLAY=${DISPLAY}
        volumes:
          - ./volumes:/volumes
        network_mode: host

    # local-server:
    #     build: ./image_local_dns_server
    #     image: seed-local-dns-server
    #     container_name: local-dns-server-10.9.0.53
    #     tty: true
    #     cap_add:
    #             - ALL
    #     networks:
    #         seed-net:
    #             ipv4_address: 10.9.0.53
                  
    # user:
    #     build: ./image_user
    #     image: seed-user
    #     container_name: user-10.9.0.5
    #     tty: true
    #     cap_add:
    #             - ALL
    #     networks:
    #         seed-net:
    #             ipv4_address: 10.9.0.5

    # attacker:
    #     image: handsonsecurity/seed-ubuntu:large 
    #     container_name: seed-attacker
    #     tty: true
    #     cap_add:
    #             - ALL
    #     privileged: true
    #     volumes:
    #             - ./volumes:/volumes
    #     network_mode: host

    # attacker_ns:
    #     build: ./image_attacker_ns
    #     image: seed-attacker_ns
    #     container_name: attacker-ns-10.9.0.153
    #     tty: true
    #     cap_add:
    #             - ALL
    #     networks:
    #         seed-net:
    #             ipv4_address: 10.9.0.153

# networks:
#     seed-net:
#         name: seed-net
#         ipam:
#             config:
#                 - subnet: 10.9.0.0/24

